name: Deploy Apis

on:
  workflow_dispatch:

env:
  AZURE_FIBONACCI_API_DIRECTORY: ./src/FibonacciApi
  AZURE_WEBAPP_PACKAGE_PATH: package
  AZURE_WEBAPP_NAME: FibonacciApi1
  
jobs: 
 build-deploy-fibonacci-api:

    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v2

      - name: Setup Dotnet 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        working-directory: ${{ env.AZURE_FIBONACCI_API_DIRECTORY }}

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run Azure webapp deploy'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}         
          package: '${{ env.AZURE_FIBONACCI_API_DIRECTORY}}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'    
